# -*- coding: utf-8 -*-
"""Ban TIENG VIET cua hai trang tom tat trong cua so F1 (ui/source_help_dialog.py).

Tach rieng vi day la trang HTML dai viet tay, khong phai tung chuoi ngan de dua vao
core/help_vi.json. Sua noi dung trang tieng Anh thi nho sua ca o day cho khop.
"""
from __future__ import annotations


def summary_html(p_macrodef, p_toden, p_master):
    """Tom tat 4 nguon cua phan mem goc va thu tu tra - ban tieng Viet."""
    return (
        "<h2>Chức năng của khối được quy định ở đâu trong phần mềm gốc</h2>"
        "<h3>1. Sổ tay lập trình (PDF) &mdash; giải thích bằng lời</h3>"
        "Đây là nguồn DUY NHẤT có lời giải thích, bảng chân lý và công thức. Muốn xem khối "
        "nào thì tìm chuỗi <code>&lt;mã&gt;H</code>."
        "<ul><li><code>VP1-C-L2-I-CB-00019-A ... Macro Instructions.pdf</code> &mdash; các "
        "macro chung (4xxx, 5xxx). Ví dụ: <code>4011H</code> = F/F(R) ở trang PDF 29. "
        "Bảng tham số bắt đầu từ trang 191.</li>"
        "<li><code>VP1-C-L2-I-CB-00018-A ... TAG Macro Instructions.pdf</code> &mdash; macro "
        "tag và macro trạm (82xx). Ví dụ: <code>820DH</code> = MV-POS ở trang PDF 116.</li>"
        "<li>Sổ tay KHÔNG nói tới: các macro đã lỗi thời (obs) và họ HCNT 20xx / 21xx.</li></ul>"
        "<h3>2. <code>%s</code> (SQLite) &mdash; tên và thông tin chính thức</h3>"
        "<ul><li><code>DEF_MACRO</code> (LANGUAGE = 'E'): mã, ký hiệu Int / Real, tên viết tắt, "
        "tên đầy đủ, loại, số chân vào / chân ra / tham số.</li>"
        "<li><code>DEF_MACRO_PIN</code>: vị trí các chân. <code>DEF_MACRO_TYPE</code>: nhóm macro.</li>"
        "<li>Chỉ có tên &mdash; file này không cho biết khối hoạt động ra sao.</li></ul>"
        "<h3>3. <code>%s</code> và <code>TAG_MCR.DEF</code> &mdash; logic chính xác mà bộ "
        "điều khiển chạy</h3>"
        "<ul><li>Mỗi macro có một thân lệnh <code>.DEF &lt;ký hiệu&gt; ... .DEFEND</code>. "
        "TODEN.DEF chứa macro chung; TAG_MCR.DEF chứa macro tag và macro trạm.</li>"
        "<li>Ký hiệu Real có tiền tố <code>F_</code> thì trong file được ghi KHÔNG có tiền tố "
        "(<code>F_T_B1_I</code> &rarr; <code>T_B1_I</code>).</li>"
        "<li>Thân lệnh của timer khác nhau giữa các loại CPU: phải dùng thư mục đúng với CPU "
        "của file .db (<code>CAD_CPU.CPUTYPE</code>).</li></ul>"
        "<h3>4. <code>%s</code> và <code>macro_param.csv</code> &mdash; danh mục và giới hạn "
        "tham số</h3>"
        "<ul><li>macro_master.csv: mã, ký hiệu, số chân và số tham số, tên tiếng Anh và tiếng Nhật.</li>"
        "<li>macro_param.csv: với từng tham số &mdash; là chữ hay số, có chỉnh được khi đang "
        "chạy không, giá trị mặc định, lớn nhất, nhỏ nhất.</li>"
        "<li>Cả hai file dùng bảng mã cp932 (tiếng Nhật).</li></ul>"
        "<h3>Thứ tự tra cứu</h3>"
        "<ol><li>Lấy <code>MACROCODE</code> của khối (bảng <code>CAD_BLOCK</code> trong file .db).</li>"
        "<li>MacroDef.db hoặc macro_master.csv &rarr; tên và ký hiệu.</li>"
        "<li>PDF, tìm <code>&lt;mã&gt;H</code> &rarr; khối dùng để làm gì.</li>"
        "<li>TODEN.DEF / TAG_MCR.DEF, tìm <code>.DEF &lt;ký hiệu&gt;</code> &rarr; logic chính xác.</li>"
        "<li>macro_param.csv &rarr; giá trị mặc định và giới hạn của tham số.</li></ol>"
        % (p_macrodef, p_toden, p_master))


def app_summary_html():
    """Tom tat: chuc nang khoi trong app nay nam o file nao - ban tieng Viet."""
    return (
        "<h2>Chức năng của khối được quy định ở đâu trong app này</h2>"
        "<h3>1. Tên và chân &mdash; chép từ nguồn của hãng</h3>"
        "<ul><li><code>core/macro_catalog.json</code> &mdash; 986 macro: tên, nhóm, số chân và "
        "số tham số.</li>"
        "<li><code>core/macro_pins.json</code> &mdash; 1.019 ký hiệu: vị trí và tên chân "
        "(lấy từ MacroDef.db).</li>"
        "<li><code>core/macro_manual.json</code> &mdash; 315 mã: tên chân và lời giải thích "
        "ngắn lấy từ sổ tay.</li></ul>"
        "<h3>2. Hành vi &mdash; bộ mô phỏng chạy cái gì</h3>"
        "<ul><li><code>core/logic_sem.json</code> (130 mã) &mdash; cổng logic, mạch chốt và "
        "timer (khóa <code>op</code>, <code>tmr</code>), chạy bởi <code>core/sheet_sim.py</code>.</li>"
        "<li><code>core/analog_sem.json</code> (262 mã) &mdash; phép toán analog, F(x), bộ so "
        "sánh, chạy bởi <code>core/sheet_sim.py</code>.</li>"
        "<li><code>core/sheet_dyn.py</code> &mdash; danh sách mã của các khối có &ldquo;trí "
        "nhớ&rdquo; (tích phân, vi phân, trễ bậc nhất, giới hạn tốc độ thay đổi, trễ thuần, "
        "lead / lag, so sánh có vùng trễ, timer); chúng được tính lại sau mỗi bước thời gian dt.</li>"
        "<li><code>core/def_sim.py</code> &mdash; khối trạm (MV/SV) và khối TAG chạy đúng thân "
        "lệnh gốc của hãng trong TAG_MCR.DEF, đọc bởi <code>core/macro_def.py</code>. Trạm nào "
        "không có thân lệnh gốc thì dùng mô hình dựng tay trong "
        "<code>core/macro_analog.json</code> (<code>core/analog_sim.py</code>).</li>"
        "<li><code>core/macro_behavior.json</code> &mdash; họ MOV trong cửa sổ Simulate block "
        "(<code>core/logic_sim.py</code>).</li>"
        "<li><code>core/macro_iodep.json</code> &mdash; đầu vào nào quyết định đầu ra nào, dùng "
        "khi dò đường đi của tín hiệu.</li>"
        "<li>Khi mô phỏng, các khối chung CHƯA chạy thân lệnh TODEN.DEF "
        "(<code>USE_TODEN = False</code> trong <code>core/def_sim.py</code>).</li></ul>"
        "<h3>3. Cửa sổ Help, tham số và ký hiệu</h3>"
        "<ul><li><code>core/block_help.py</code> &mdash; lời giải thích, chọn theo op / họ timer "
        "trong logic_sem.json và analog_sem.json, nên lời giải thích luôn khớp với bộ mô phỏng.</li>"
        "<li><code>core/manual_index.json</code> &mdash; đoạn giải thích chép từ hai sổ tay "
        "PDF, hiện ngay bên dưới; với khối không có op / timer thì đây là phần chữ duy nhất.</li>"
        "<li><code>core/module_docs.json</code> &mdash; cho các khối giao tiếp card EHC (VPCL, "
        "FDCL, PLUL): card làm gì (chép từ tài liệu phần cứng DEHC), các trang EHC.pdf có vẽ "
        "logic của card, và ý nghĩa từng tham số (SN, DI, FI, DO, CO, FO) đọc từ thân lệnh "
        "trong TODEN.DEF.</li>"
        "<li><code>core/help_i18n.py</code> + <code>core/help_vi.json</code> + "
        "<code>core/help_vi_manual.json</code> &mdash; bản dịch tiếng Việt viết tay cho Help "
        "và F1 (nút English / Tiếng Việt).</li>"
        "<li><code>core/block_timing.py</code> giản đồ xung, <code>core/block_logic.py</code> "
        "sơ đồ cổng logic, <code>core/block_fbd.py</code> sơ đồ khối chức năng (cả hai vẽ từ "
        "thân lệnh DEF của hãng), <code>core/block_curve.py</code> đường đặc tính và bảng giá trị.</li>"
        "<li><code>core/block_params.py</code> &mdash; giá trị tham số đọc từ "
        "<code>CAD_BLOCK_PARAM</code> trong file .db, giới hạn lấy từ macro_param.csv.</li>"
        "<li><code>core/macro_internal.json</code> + <code>core/internal_figs/</code> &mdash; 69 "
        "hình vẽ bên trong khối, cắt từ sổ tay.</li>"
        "<li><code>core/symbol_shapes.json</code> + <code>core/block_syms.py</code> &mdash; ký "
        "hiệu khối vẽ trên bản vẽ.</li></ul>"
        "<h3>Thứ tự tra cứu</h3>"
        "<ol><li>macro_catalog.json &rarr; tên.</li>"
        "<li>logic_sem.json &rarr; khối số (0/1); không có thì xem analog_sem.json.</li>"
        "<li>Mã nằm trong một danh sách của sheet_dyn.py &rarr; được tính theo thời gian ở đó.</li>"
        "<li>Có thân lệnh gốc trong TAG_MCR.DEF và app làm được mọi lệnh trong đó &rarr; "
        "def_sim.py; trạm không có thân lệnh &rarr; macro_analog.json.</li>"
        "<li>Họ MOV &rarr; macro_behavior.json (cửa sổ Simulate block).</li></ol>")
